# Generated by Django 3.0.5 on 2020-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200512_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewname', models.CharField(max_length=100)),
                ('reviewbody', models.TextField()),
            ],
        ),
    ]
