# Generated by Django 3.0.5 on 2020-05-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
